Raise required toolchain to rust 1.53
Required by the dependency on indicatif:

    error[E0658]: use of unstable library feature 'debug_non_exhaustive'
       --> github.com-1ecc6299db9ec823/indicatif-0.17.0/src/multi.rs:388:14
        |
    388 |             .finish_non_exhaustive()
        |              ^^^^^^^^^^^^^^^^^^^^^

    error[E0658]: use of unstable library feature 'duration_zero'
       --> github.com-1ecc6299db9ec823/indicatif-0.17.0/src/progress_bar.rs:169:21
        |
    169 |         if interval.is_zero() {
        |                     ^^^^^^^

    error[E0658]: use of unstable library feature 'duration_zero'
       --> github.com-1ecc6299db9ec823/indicatif-0.17.0/src/progress_bar.rs:601:33
        |
    601 |         debug_assert!(!interval.is_zero());
        |                                 ^^^^^^^